image: docker:20.10.11

services:
  - docker:20.10.11-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  CI_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  ANSIBLE_PATH: /builds/ansible-playbook/oci_storage_exporter-playbook

stages:
  - build
  - deploy

Build-image:
  stage: build
  except:
    changes:
      - "README.md"
      # - ".gitlab-ci.yml"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $CI_IMAGE .
    - docker push $CI_IMAGE
  tags:
    - docker-runner
  

Deploy-container:
  image: gitlab-registry.sysagecloud.com:5050/ansible/sysage-ansible-runner:latest
  stage: deploy
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sysagecloud.com/Boking/msp-project-playbook.git
    - cp $ANSIBLE_HOST_FILE msp-project-playbook/host
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ANSIBLE_PRIVATE_KEY")
    - echo "$SSH_KNOWN_HOSTS" >> /root/.ssh/known_hosts
    - chmod 644 /root/.ssh/known_hosts
  script:
    - ansible-playbook -i msp-project-playbook/host -e host=dev-master -e image=$CI_IMAGE msp-project-playbook/azure-storage-exporter/deploy-container.yml
  needs:
    - Build-image
  tags:
    - docker-runner